version: '3'

services:
  db:
    image: postgres
    ports:
      - "9000:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - PGPASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
volumes:
  pgdata:
